### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by elronio** [avinash8526/Murgi#1]
File "aviconv.py", line 13
print os.getcwd()
          ^
SyntaxError: invalid syntax

**Comment by avinash8526** [comment]
Hi elronio,

I developed this considering python 2.7,  you might be having newer version of python in which print statement has different syntax, Further I will remove all print statement and then it should work fine for you.
Thanks for pointing out.

Commit 13f265e2cac766fee5bc72b9d83f185c55e5f542
