### ISSUE TITLE
Report is does not contain any data or graphs

### ISSUE THREAD

**Issue by elronio** [avinash8526/Murgi#4]
![image](https://cloud.githubusercontent.com/assets/11079737/6474979/8d03d50a-c1ba-11e4-8671-88342f813b59.png)

I would attach the .trx file but I can't on here or if there is a way for me to post the code to share.

**Comment by avinash8526** [comment]
Hi,

Please send me the .trx file on my email avinash8526@gmail.com , I will look into this..

**Comment by avinash8526** [comment]
closed , the trx param were different than expected may be due to change in VS version now it works fine as added new files in generictestresult

![screen shot 2015-03-05 at 7 11 15 am](https://cloud.githubusercontent.com/assets/2865238/6497518/e4f809e6-c306-11e4-99a5-a411fcbd4e6d.png)
